### ISSUE TITLE
Expound readme.MD

### ISSUE THREAD

**Issue by ConorOBrien-Foxx** [The-Quill/Adynata#2]
![I now have additional questions.](http://i.imgur.com/jN57tGt.png)

**Comment by RikerW** [comment]
Is this a Sass-off?

**Comment by epicTCK** [comment]
It's on...

**Comment by Maltysen** [comment]
@RikerW no its a Less-off.

ba-dum tsssss...

**Comment by The-Quill** [comment]
I relent; you win. Fixed in d75169b
